# Generated by Django 5.0.4 on 2024-04-29 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_product_quantity_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="count",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
