# Generated by Django 5.0.4 on 2024-04-29 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_order_orderproduct"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderproduct",
            options={},
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("pickup", "Olib ketish"), ("delivery", "Yetkazib berish")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="count",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="orderproduct",
            table="order_products",
        ),
    ]
