# Generated by Django 5.0.4 on 2024-04-30 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_orderproduct_options_remove_orderproduct_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
