# Generated by Django 5.0.4 on 2024-05-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_remove_category_description_and_more"),
        ("users", "0008_alter_address_latitude_alter_address_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="secondary_phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
