# Generated by Django 5.0.4 on 2024-05-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_alter_product_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_processing", "Jarayonda"),
                    ("confirmed", "Tasdiqlangan"),
                    ("performing", "Amalga oshirilyabdi"),
                    ("success", "Yetkazib berilgan"),
                    ("canceled", "Bekor qilingan"),
                ],
                default="in_processing",
                max_length=255,
            ),
        ),
    ]
