# Generated by Django 5.0.4 on 2024-05-03 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
    ]
