# Generated by Django 5.0.4 on 2024-05-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_remove_productimage_product_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("pickup", "Олиб кетиш"), ("delivery", "Етказиб бериш")],
                default="delivery",
                max_length=20,
                verbose_name="Етказиб бериш тури",
            ),
        ),
    ]
