# Generated by Django 5.0.4 on 2024-05-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="external_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
